---
- name: Ubuntu Web Dev Machine
  hosts: 127.0.0.1
  connection: local
  vars:
    hostname: localhost
    downloadDir: /home/{{ ansible_ssh_user }}/Download/Downloads-Ubuntu-Like-A-Pro
    installDir: /home/{{ ansible_ssh_user }}/Apps
    downloadThreads: 20

  roles:
      - initial
      - system_essential
# Order of "initial" and "system_essentials" roles is important ! Keep it at the top.
      - ide
      - browser
      - system_general
      - web_dev_essential
      - web_dev_tools
      - media
      - tweak
