---
- name: Install Composer Packages
  shell: "composer global require {{ item }}"
  with_items:
    - squizlabs/php_codesniffer=*
    - dealerdirect/phpcodesniffer-composer-installer
    - sirbrillig/phpcs-variable-analysis
    - phpcompatibility/php-compatibility
    - phpcompatibility/phpcompatibility-wp
    - automattic/vipwpcs
    - automattic/phpcs-neutron-standard
    - wp-cli/wp-cli
