---
- name: Get Azure installer
  get_url:
    url: https://aka.ms/InstallAzureCLIDeb
    path: {{ downloadDir }}

- name: Run Azure setup script
  shell: bash {{ downloadDir }}/InstallAzureCLIDeb
  become: yes