---
- name: Get Azure installer
  get_url:
    url: https://aka.ms/InstallAzureCLIDeb
    dest: "{{ downloadDir }}"

- name: Run Azure setup script
  shell: bash {{ downloadDir }}/InstallAzureCLIDeb
  become: yes