---
- name: Check if Composer is installed.
  stat: "path=$(which composer)"
  register: composer_bin

- name: Get Composer installer signature.
  uri:
    url: https://composer.github.io/installer.sig
    return_content: true
  register: composer_installer_signature
  when: not composer_bin.stat.exists

- name: Download Composer
  get_url:
    url: https://getcomposer.org/installer
    dest: "{{ downloadDir }}"
    mode: a+x
    checksum: "sha384:{{ composer_installer_signature.content }}"
  when: not composer_bin.stat.exists

- name: Run Composer installer.
  shell: |
    {{ php_executable }} composer-installer.php {% if composer_version %} --version={{ composer_version }}{% endif %}
    chdir={{ downloadDir }}
  when: not composer_bin.stat.exists

- name: Move Composer to /usr/local/bin
  shell: creates="/usr/local/bin/composer" mv {{ downloadDir }}/composer.phar /usr/local/bin/composer
  become: yes
  when: not composer_bin.stat.exists

- name: Update Composer to latest version (if configured).
  command: >
    {{ php_executable }} {{ composer_path }} self-update
  register: composer_update

- name: Add GitHub OAuth token for Composer (if configured).
  become: true
  become_user: "{{ ansible_user }}"
  template:
    src: "auth.json.j2"
    dest: "~.composer/auth.json"
    owner: "{{ ansible_user }}"
  when: githubOauthToken | length > 0

- name: Install Composer Packages
  shell: "composer global require {{ item }}"
  with_items:
    - squizlabs/php_codesniffer=*
    - dealerdirect/phpcodesniffer-composer-installer
    - sirbrillig/phpcs-variable-analysis
    - phpcompatibility/php-compatibility
    - phpcompatibility/phpcompatibility-wp
    - automattic/vipwpcs
    - automattic/phpcs-neutron-standard
    - wp-cli/wp-cli
