---
- name: Check if Composer is installed.
  command: "which composer"
  register: composer_bin
  ignore_errors: yes

- name: Get Composer installer signature.
  uri:
    url: https://composer.github.io/installer.sig
    return_content: true
  register: composer_installer_signature
  when: not composer_bin

- name: Download Composer
  get_url:
    url: https://getcomposer.org/installer
    dest: "{{ downloadDir }}/composer-setup.php"
    mode: a+x
    checksum: "sha384:{{ composer_installer_signature.content }}"
  when: not composer_bin

- name: Run Composer installer.
  shell: php {{downloadDir}}/composer-setup.php
  when: not composer_bin

- name: Move Composer to /usr/local/bin
  shell: |
    mv {{ downloadDir }}/composer.phar /usr/local/bin/composer
    chmod +x /usr/local/bin/composer
  become: yes
  when: not composer_bin

- name: Update Composer to Latest Version
  shell: /usr/local/bin/composer

- name: Add GitHub OAuth Token for Composer (if configured)
  become: true
  become_user: "{{ ansible_user }}"
  template:
    src: "auth.json.j2"
    dest: "~.composer/auth.json"
    owner: "{{ ansible_user }}"
  when: githubOauthToken | length > 0

- name: Install Composer Packages
  shell: "composer global require {{ item }}"
  with_items:
    - squizlabs/php_codesniffer=*
    - dealerdirect/phpcodesniffer-composer-installer
    - sirbrillig/phpcs-variable-analysis
    - phpcompatibility/php-compatibility
    - phpcompatibility/phpcompatibility-wp
    - automattic/vipwpcs
    - automattic/phpcs-neutron-standard
    - wp-cli/wp-cli
