---
- name: Check if Composer is installed.
  command: "which composer"
  register: composer_bin
  ignore_errors: yes

- name: Install Composer
  shell: |
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    php -r "if (hash_file('sha384', 'composer-setup.php') === 'e0012edf3e80b6978849f5eff0d4b4e4c79ff1609dd1e613307e16318854d24ae64f26d17af3ef0bf7cfb710ca74755a') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    php composer-setup.php
    php -r "unlink('composer-setup.php');"
  when: not composer_bin

- name: Move Composer to /usr/local/bin
  shell: |
    mv {{ downloadDir }}/composer.phar /usr/local/bin/composer
    chmod +x /usr/local/bin/composer
  become: yes
  when: not composer_bin

- name: Update Composer to Latest Version
  shell: composer self-update

- name: Install Composer Packages
  shell: "composer global require {{ item }}"
  with_items:
    - squizlabs/php_codesniffer=*
    - dealerdirect/phpcodesniffer-composer-installer
    - sirbrillig/phpcs-variable-analysis
    - phpcompatibility/php-compatibility
    - phpcompatibility/phpcompatibility-wp
    - automattic/vipwpcs
    - automattic/phpcs-neutron-standard
    - wp-cli/wp-cli
