---
- name: Install kubectl
  shell: |
    cd {{ downloadDir }}
    curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
    chmod +x ./kubectl
    mv ./kubectl /usr/local/bin/kubectl
  become: yes

- name: Install kubectx, kubens and bash completions
  shell: |
    cd {{ installDir }}
    curl -s https://github.com/ahmetb/kubectx.git
    cd kubectx
    chmod +x kubectx
    chomd +x kubens
    mv kubectx /usr/local/bin/
    mv kubens /usr/local/bin/
  become: yes

- name: Add Completions
  shell: |
    cd {{ installDir }}/kubectx
    mkdir -p ~/.oh-my-zsh/completions
    chmod -R 755 ~/.oh-my-zsh/completions
    ln -s ./completion/kubectx.zsh ~/.oh-my-zsh/completions/_kubectx.zsh
    ln -s ./completion/kubens.zsh ~/.oh-my-zsh/completions/_kubens.zsh