---
- name: Ensure Ondrej PHP repo added
  apt_repository: repo='ppa:ondrej/php' state=present update_cache=yes
  become: yes

- name: Ensure PHP installed
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - php
    - php-dev
    - php-cli
    - php-json
    - php-mysql
    - php-curl
    - php-gd
    - php-xdebug
    - php-mbstring
    - mysql-client
  become: yes

- name: Set php_executable variable to a default if not defined.
  set_fact:
    php_executable: php
  when: php_executable is not defined