---
- name: Install Siege
  get_url:
    url: http://download.joedog.org/siege/siege-latest.tar.gz
    dest: "{{ installDir }}"

- name: Configure and build Siege
  shell: |
    cd {{ installDir }}
    mkdir siege
    tar -xzf siege-latest.tar.gz -C siege
    cd siege/*
    ./configure
    make

- name: Install Siege
  shell: make install
  become: yes