---
- name: Install prerequisites
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg2' ,'software-properties-common']
    update_cache: yes

- name: Add Docker GPG key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{docker_distribution_string|lower}} {{docker_distribution_release|lower}} stable

- name: Install Docker
  apt:
    name: docker-ce
    update_cache: yes

- name: Add Docker group
  shell: |
    usermod -aG docker $USER
    newgrp docker
  become: yes

- name: Install prerequisites
  apt:
    name: ['python3-pip', 'python3-setuptools', 'virtualenv']
    update_cache: yes

- name: Install docker-compose
  shell: axel -n {{ downloadThreads }} "https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  become: yes
  wait_for:
    path: /usr/local/bin/docker-compose