---
- name: Install PHP
  include: php.yml

- name: Download Composer
  shell: creates="composer.phar" curl -s http://getcomposer.org/installer | php chdir={{ downloadDir }}

- name: Move Composer to /usr/local/bin
  shell: creates="/usr/local/bin/composer" mv {{ downloadDir }}/composer.phar /usr/local/bin/composer
  sudo: yes

- name: Make Composer executable
  shell: chmod +x /usr/local/bin/composer
  sudo: yes

- name: Install Ruby
  include: ruby.yml

- name: Install Docker CE
  include: docker.yml
