---
- name: Ensure ZSH installed
  apt: pkg=zsh state=latest
  become: yes

- name: Check for existing OMZ dir
  stat:
    path: /home/{{ ansible_user }}/.oh-my-zsh
  register: stat_result

- name: Get Oh-My-ZSH
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  become: yes
  when: stat_result.stat.exists == False

- name: Change theme for user
  replace:
    path: /home/{{ ansible_user }}/.zshrc
    regexp: '^ZSH_THEME="robbyrussell"'
    replace: '^ZSH_THEME="agnoster"'

- name: Change default shell for user
  shell: chsh {{ ansible_user }} -s $(which zsh)
  ignore_errors: yes

- name: Change default shell for root
  shell: chsh root -s $(which zsh)
  ignore_errors: yes