---
- name: update APT cache
  apt: update_cache=yes
  become: yes

- name: create directories
  file: path="{{ item }}" state=directory
  with_items:
    - "{{ downloadDir }}"
    - "{{ installDir }}"
