---
- name: ensure system packages are installed
  apt: pkg="{{ item }}" state=latest
  with_items:
    - ubuntu-restricted-extras
    - ubuntu-restricted-addons
    - build-essential
    - git
    - curl
    - wget
    - bash-completion
    - axel
    - aria2
    - htop
    - mc
    - libpq-dev
    - build-essential
    - gcc
    - openssl
    - dconf-tools
    - python-software-properties
    - python-apt
    - python-mysqldb
    - python-psycopg2
    - ca-certificates
    - libsecret-1-dev
    - net-tools
    - libnss3-tools
    - snapd
    - virtualbox
    - zsh
  sudo: yes

- name: Update caches after PPA being added
  apt: update_cache=yes
  sudo: yes

- include: zsh.yml
