---
- name: Ensure ZSH installed
  apt: pkg=zsh state=latest
  sudo: yes

- name: Check for existing OMZ dir
  stat:
    path: /home/{{ ansible_ssh_user }}/.oh-my-zsh
  register: stat_result

- name: Get Oh-My-ZSH
  shell: creates="/home/{{ ansible_ssh_user }}/.oh-my-zsh" su - {{ ansible_ssh_user }} -c 'wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | sed -n '/chsh/!p' | zsh'
  sudo: yes
  when: stat_result.stat.exists == False

- name: Change theme for user
  shell: sed -i 's/ZSH_THEME="robbyrussell"/ZSH_THEME="agnoster"/' /home/{{ ansible_ssh_user }}/.zshrc

- name: Change default shell for user
  shell: chsh {{ ansible_ssh_user }} -s $(which zsh)
  ignore_errors: yes