---
- name: Download Chrome Latest
  get_url:
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest: "{{ downloadDir }}"

- name: Install Chrome
  shell: dpkg -i google-chrome-stable_current_amd64.deb
  become: yes

- name: Install Chromium Stable
  apt: name="{{ item }}" state=present
  with_items:
    - chromium-browser
  become: yes
