---
- name: Add Browser repositories
  apt_repository: repo="{{ item }}" state=present
  with_items:
    - deb http://dl.google.com/linux/chrome/deb/ stable main
    - ppa:chromium-daily/stable
    - deb http://deb.opera.com/opera/ stable non-free
  sudo: yes


- name: Import Browser repo keys
  apt_key: url="{{ item }}" state=present
  with_items:
    - https://dl-ssl.google.com/linux/linux_signing_key.pub
  sudo: yes


- name: Update caches after repos being added
  apt: update_cache=yes
  sudo: yes

- name : Install Chromium Stable
  apt: name="{{ item }}" state=present
  with_items:
    - google-chrome-stable
    - chromium-browser
  sudo: yes
