---
- name: Install Chrome
  shell: |
    wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dpkg -i google-chrome-stable_current_amd64.deb
  become: yes

- name: Install Chromium Stable
  apt: name="{{ item }}" state=present
  with_items:
    - chromium-browser
  become: yes
